Make it easier to rum mwmbl locally
mwmbl/mwmbl pull request #78
Opened 2022-12-07 20:03 UTC by daoudclarke

Fixes #48

2022-12-08 03:28 UTC, omasanori requested changes
Thank you so much for your consideration! I tested Docker setup but unfortunately it still fails.

2022-12-08 03:28 UTC, omasanori commented on Dockerfile
>  EXPOSE 5000
Please copy `devdata/index-v2.tinysearch` to somewhere in the image (`/data`?) for the moment. In long term, we may revisit https://github.com/mwmbl/mwmbl/issues/27 for a better workflow.

2022-12-08 03:28 UTC, omasanori commented on Dockerfile
> +CMD ["/venv/bin/mwmbl-tinysearchengine", "--num-pages", "10240000", "--background"]
Add `--data /data` here if `index-v2.tinysearch` is placed into there.

2022-12-08 03:28 UTC, omasanori commented on README.md
> +WARNING: this uses production settings and creates a **very** large index (around 40Gb)
It is fine for now, I think.

2022-12-08 03:28 UTC, omasanori commented on README.md
> +3. Run `$ docker run -p 8080:8080 mwmbl`
Don't we need PostgreSQL on Docker setup, by the way?

2022-12-08 03:59 UTC, omasanori commented on Dockerfile
>  EXPOSE 5000
Adding `ADD devdata/index-v2.tinysearch /app/devdata/` seems fine.

2022-12-08 04:09 UTC, omasanori commented
Simply requiring Dokku as described at https://github.com/mwmbl/mwmbl/wiki/Deployment might be easier for now.

2022-12-19 21:50 UTC, daoudclarke commented
Merging this now, any further issues can be dealt with in a separate PR.

2022-12-19 21:50 UTC, merged